<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PicAFlick.Data\PicAFlick.Data.csproj" />
    <ProjectReference Include="..\PicAFlick.Domain\PicAFlick.Domain.csproj" />
    <ProjectReference Include="..\PicAFlick.Infrastructure.Tmdb\PicAFlick.Infrastructure.Tmdb.csproj" />
  </ItemGroup>

</Project>
